### ISSUE TITLE
Purchase Confirmation E-mail

### ISSUE THREAD

**Issue by sebasalvarado** [YoSoyBacan/platform#31]
## Tasks:

- [ ] Change `mjml` template to show a summary table of the purchase and the amount processed.

- [ ] Add informative Copy to the email that helps the customer know how to redeem their voucher.

- [ ] Add a link to WhatsApp / Email to call us in case of any questions.
