### ISSUE TITLE
Registration Confirmation Email

### ISSUE THREAD

**Issue by sebasalvarado** [YoSoyBacan/platform#36]
## Description:
As a newly registered business, I want to receive an email with a confirmation of my recent registration. I want to make sure that all my details look correct and I want to know what are the next steps.

## Tasks:

- [ ] Design a registration e-mail template form MJML.
- [ ] Get copy and content from marketing team to help answer and many customer questions as possible.
- [ ] Implement the automated email to be sent as confirmation of registration.
